# Generated by Django 5.2.6 on 2025-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='epis_fornecidos',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
